---
title: "Home"
---

### Description and context
This is a static webpage created to track the progress of a survey on Mexico WSS Operators. The survey is part of a larger effort to collect original data in preparation of the publication **"Development in America" 2020** that will focus on Infrastructure. This specific survey is sponsored by the **Interamerican Development Bank (IADB)**, Water Division, Knowledge Team  [WSA Knowledge](https://idbg.sharepoint.com/sites/WSAknowledge), where I work as a consultant. 

### Content
This webpage http://mexicowatersurvey.lulliter.com/ has been built as an `R Markdown website`, using `Jekyll` as a static site generator with `GitHub Pages` - actually redirected to my custom domain on `AWS`. 

The code for the page is on my [Github repo](https://github.com/Lulliter/MexicoWaterSurvey), which is actually a sud-directory of the research project. The latter (not publicly disclosed because includes confidential data) is on the IADB company OneDrive cloud. 	

### Creators
This page was created by Luisa Mimmi (lmm76@georgetown.edu or lmmimmi@iadb.org) but builds on data collected by various IADB colleagues and partner organizations. See [**Info page**](http://mexicowatersurvey.lulliter.com/info.html) for all due credits. 

### WARNING
Please note, as of today _(`r format(Sys.time(), '%d %B, %Y')`)_ this is still a work in progress, subject to change and not ready for dissemination.
<!-- <span style="color:red">Please note, this is still a work in progress, subject to change and not ready for dissemination.</span>. -->
